// const BASE_URL = 'https://angular.dev/assets/images/tutorials/common';

// const HOUSE_LIST = [
//     {
//       id: 0,
//       name: 'Идеальное жилье для нового старта',
//       city: 'Чикаго',
//       state: 'Иллинойс',
//       photo: `${BASE_URL}/bernard-hermant-CLKGGwIBTaY-unsplash.jpg`,
//       rooms: 4,
//       wifi: true,
//       laundry: true,
//     },
//     {
//       id: 1,
//       name: 'A113 Новый корпус',
//       city: 'Санта-Моника',
//       state: 'Калифорния',
//       photo: `${BASE_URL}/brandon-griggs-wR11KBaB86U-unsplash.jpg`,
//       rooms: 2,
//       wifi: false,
//       laundry: true,
//     },
//     {
//       id: 2,
//       name: 'Теплые Кровати',
//       city: 'Джуно',
//       state: 'Аляска',
//       photo: `${BASE_URL}/i-do-nothing-but-love-lAyXdl1-Wmc-unsplash.jpg`,
//       rooms: 1,
//       wifi: false,
//       laundry: false,
//     },
//     {
//       id: 3,
//       name: 'Приусадебное жилье',
//       city: 'Чикаго',
//       state: 'Иллинойс',
//       photo: `${BASE_URL}/ian-macdonald-W8z6aiwfi1E-unsplash.jpg`,
//       rooms: 1,
//       wifi: true,
//       laundry: false,
//     },
//     {
//       id: 4,
//       name: 'Группа "Счастливые дома"',
//       city: 'Гэри',
//       state: 'Индиана',
//       photo: `${BASE_URL}/krzysztof-hepner-978RAXoXnH4-unsplash.jpg`,
//       rooms: 1,
//       wifi: true,
//       laundry: false,
//     },
//     {
//       id: 5,
//       name: 'Прекрасные аппартаменты',
//       city: 'Окленд',
//       state: 'Калифорния',
//       photo: `${BASE_URL}/r-architecture-JvQ0Q5IkeMM-unsplash.jpg`,
//       rooms: 2,
//       wifi: true,
//       laundry: true,
//     },
//     {
//       id: 6,
//       name: 'Действительно безопасные дома',
//       city: 'Окленд',
//       state: 'Калифорния',
//       photo: `${BASE_URL}/phil-hearing-IYfp2Ixe9nM-unsplash.jpg`,
//       rooms: 5,
//       wifi: true,
//       laundry: true,
//     },
//     {
//       id: 7,
//       name: 'Hopeful Housing Solutions',
//       city: 'Окленд',
//       state: 'Калифорния',
//       photo: `${BASE_URL}/r-architecture-GGupkreKwxA-unsplash.jpg`,
//       rooms: 1,
//       wifi: true,
//       laundry: true,
//     },
//     {
//       id: 8,
//       name: 'Надежные жилищные решения',
//       city: 'Окленд',
//       state: 'Калифорния',
//       photo: `${BASE_URL}/saru-robert-9rP3mxf8qWI-unsplash.jpg`,
//       rooms: 3,
//       wifi: false,
//       laundry: false,
//     },
//     {
//       id: 9,
//       name: 'Столичные кварталы',
//       city: 'Портленд',
//       state: 'Орегон',
//       photo: `${BASE_URL}/webaliser-_TPTXZd9mOo-unsplash.jpg`,
//       rooms: 2,
//       wifi: true,
//       laundry: true,
//     },
//   ];